version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "20000:20000"
  web-crac:
    build:
      context: .
      dockerfile: Dockerfile-crac
    ports:
      - "20000:20000"
