FROM azul/zulu-openjdk:21 AS builder
WORKDIR /app
COPY ./ ./
RUN ./gradlew clean npmRunBuild build -x test --no-daemon --stacktrace

FROM azul/zulu-openjdk:21-jdk-crac AS crac-checkpoint
WORKDIR /app
COPY --from=builder /app/build/libs/app.jar ./app.jar
RUN mkdir checkpoint
RUN java -Dspring.context.checkpoint=onRefresh -XX:CRaCCheckpointTo=checkpoint -jar app.jar

FROM azul/zulu-openjdk:21-jdk-crac
WORKDIR /app
COPY --from=crac-checkpoint /app/checkpoint ./checkpoint
EXPOSE 20000
ENTRYPOINT ["java", "-XX:CRaCRestoreFrom=checkpoint"]
