name: Auto-Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened

jobs:
  auto-merge-dependabot-prs:
    name: Auto-Merge Dependabot Dependency PR
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write

    steps:
      - name: Comment to trigger Dependabot merge
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr comment $PR_NUMBER --body "@dependabot merge"
